/* Generated by Yosys 0.51+46 (git sha1 8bde6ac17, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module SPI_SLAVE(MOSI, tx_valid, clk, rst_n, ss_n, tx_data, MISO, rx_valid, rx_data);
  wire [9:0] _000_;
  wire _001_;
  wire _002_;
  wire [3:0] _003_;
  wire [2:0] _004_;
  wire [2:0] _005_;
  wire [9:0] _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire [3:0] _081_;
  wire [3:0] _082_;
  wire [3:0] _083_;
  wire [9:0] _084_;
  wire ADD_DATA_checker;
  output MISO;
  wire MISO;
  input MOSI;
  wire MOSI;
  wire [9:0] bus;
  input clk;
  wire clk;
  wire [3:0] counter1;
  wire [2:0] counter2;
  wire [2:0] cs;
  input rst_n;
  wire rst_n;
  output [9:0] rx_data;
  wire [9:0] rx_data;
  output rx_valid;
  wire rx_valid;
  input ss_n;
  wire ss_n;
  input [7:0] tx_data;
  wire [7:0] tx_data;
  input tx_valid;
  wire tx_valid;
  sky130_fd_sc_hd__clkinv_1 _085_ (
    .A(ADD_DATA_checker),
    .Y(_061_)
  );
  sky130_fd_sc_hd__clkinv_1 _086_ (
    .A(MOSI),
    .Y(_062_)
  );
  sky130_fd_sc_hd__clkinv_1 _087_ (
    .A(bus[4]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__clkinv_1 _088_ (
    .A(counter1[3]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor2_1 _089_ (
    .A(cs[0]),
    .B(cs[1]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__o21ai_0 _090_ (
    .A1(cs[0]),
    .A2(cs[1]),
    .B1(rx_valid),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _091_ (
    .A(counter1[1]),
    .B(counter1[0]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand3_1 _092_ (
    .A(counter1[1]),
    .B(counter1[0]),
    .C(counter1[2]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor3b_1 _093_ (
    .A(cs[0]),
    .B(cs[1]),
    .C_N(cs[2]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _094_ (
    .A(cs[1]),
    .SLEEP(cs[2]),
    .X(_070_)
  );
  sky130_fd_sc_hd__nor2_1 _095_ (
    .A(_069_),
    .B(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _096_ (
    .A(_069_),
    .SLEEP(_070_),
    .X(_072_)
  );
  sky130_fd_sc_hd__and4_1 _097_ (
    .A(counter1[1]),
    .B(counter1[0]),
    .C(counter1[2]),
    .D(counter1[3]),
    .X(_073_)
  );
  sky130_fd_sc_hd__nand4_1 _098_ (
    .A(counter1[1]),
    .B(counter1[0]),
    .C(counter1[2]),
    .D(counter1[3]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _099_ (
    .A(_071_),
    .B(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nor3_1 _100_ (
    .A(cs[2]),
    .B(cs[0]),
    .C(cs[1]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__or3_1 _101_ (
    .A(cs[2]),
    .B(cs[0]),
    .C(cs[1]),
    .X(_077_)
  );
  sky130_fd_sc_hd__o31ai_1 _102_ (
    .A1(rx_valid),
    .A2(_071_),
    .A3(_074_),
    .B1(_066_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _103_ (
    .A(counter1[1]),
    .B(counter1[0]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor3_1 _104_ (
    .A(counter1[1]),
    .B(counter1[0]),
    .C(counter1[2]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__and3_1 _105_ (
    .A(_064_),
    .B(_072_),
    .C(_079_),
    .X(_080_)
  );
  sky130_fd_sc_hd__mux2_1 _106_ (
    .A0(bus[0]),
    .A1(MOSI),
    .S(_080_),
    .X(_000_[0])
  );
  sky130_fd_sc_hd__nand2b_1 _107_ (
    .A_N(counter1[1]),
    .B(counter1[0]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand3b_1 _108_ (
    .A_N(counter1[1]),
    .B(counter1[0]),
    .C(MOSI),
    .Y(_009_)
  );
  sky130_fd_sc_hd__xor2_1 _109_ (
    .A(counter1[2]),
    .B(_078_),
    .X(_010_)
  );
  sky130_fd_sc_hd__xnor2_1 _110_ (
    .A(counter1[2]),
    .B(_078_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__o21a_1 _111_ (
    .A1(_069_),
    .A2(_070_),
    .B1(_064_),
    .X(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _112_ (
    .A(_011_),
    .B(_012_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__o41ai_1 _113_ (
    .A1(counter1[2]),
    .A2(counter1[3]),
    .A3(_071_),
    .A4(_008_),
    .B1(bus[1]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__o21ai_0 _114_ (
    .A1(_009_),
    .A2(_013_),
    .B1(_014_),
    .Y(_000_[1])
  );
  sky130_fd_sc_hd__nand2b_1 _115_ (
    .A_N(counter1[0]),
    .B(counter1[1]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand4b_1 _116_ (
    .A_N(counter1[0]),
    .B(MOSI),
    .C(_072_),
    .D(counter1[1]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__o41ai_1 _117_ (
    .A1(counter1[3]),
    .A2(_071_),
    .A3(_010_),
    .A4(_015_),
    .B1(bus[2]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__o31ai_1 _118_ (
    .A1(counter1[3]),
    .A2(_010_),
    .A3(_016_),
    .B1(_017_),
    .Y(_000_[2])
  );
  sky130_fd_sc_hd__o41ai_1 _119_ (
    .A1(counter1[3]),
    .A2(_067_),
    .A3(_071_),
    .A4(_010_),
    .B1(bus[3]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand3_1 _120_ (
    .A(counter1[1]),
    .B(counter1[0]),
    .C(MOSI),
    .Y(_019_)
  );
  sky130_fd_sc_hd__o21ai_0 _121_ (
    .A1(_013_),
    .A2(_019_),
    .B1(_018_),
    .Y(_000_[3])
  );
  sky130_fd_sc_hd__a31oi_1 _122_ (
    .A1(counter1[2]),
    .A2(_078_),
    .A3(_012_),
    .B1(_063_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__a41o_1 _123_ (
    .A1(MOSI),
    .A2(counter1[2]),
    .A3(_078_),
    .A4(_012_),
    .B1(_020_),
    .X(_000_[4])
  );
  sky130_fd_sc_hd__xnor2_1 _124_ (
    .A(_064_),
    .B(_079_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__or3_1 _125_ (
    .A(_071_),
    .B(_011_),
    .C(_021_),
    .X(_022_)
  );
  sky130_fd_sc_hd__o41ai_1 _126_ (
    .A1(_071_),
    .A2(_008_),
    .A3(_011_),
    .A4(_021_),
    .B1(bus[5]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__o21ai_0 _127_ (
    .A1(_009_),
    .A2(_022_),
    .B1(_023_),
    .Y(_000_[5])
  );
  sky130_fd_sc_hd__o41ai_1 _128_ (
    .A1(_071_),
    .A2(_011_),
    .A3(_015_),
    .A4(_021_),
    .B1(bus[6]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__o31ai_1 _129_ (
    .A1(_011_),
    .A2(_016_),
    .A3(_021_),
    .B1(_024_),
    .Y(_000_[6])
  );
  sky130_fd_sc_hd__o31ai_1 _130_ (
    .A1(counter1[3]),
    .A2(_068_),
    .A3(_071_),
    .B1(bus[7]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__o21ai_0 _131_ (
    .A1(_019_),
    .A2(_022_),
    .B1(_025_),
    .Y(_000_[7])
  );
  sky130_fd_sc_hd__a31oi_1 _132_ (
    .A1(counter1[3]),
    .A2(_072_),
    .A3(_079_),
    .B1(bus[8]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a41oi_1 _133_ (
    .A1(_062_),
    .A2(counter1[3]),
    .A3(_072_),
    .A4(_079_),
    .B1(_026_),
    .Y(_000_[8])
  );
  sky130_fd_sc_hd__o41ai_1 _134_ (
    .A1(counter1[2]),
    .A2(_064_),
    .A3(_071_),
    .A4(_008_),
    .B1(bus[9]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2_1 _135_ (
    .A(_072_),
    .B(_021_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__o31ai_1 _136_ (
    .A1(counter1[2]),
    .A2(_009_),
    .A3(_028_),
    .B1(_027_),
    .Y(_000_[9])
  );
  sky130_fd_sc_hd__nand2_1 _137_ (
    .A(tx_valid),
    .B(_065_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a21oi_1 _138_ (
    .A1(counter2[0]),
    .A2(_029_),
    .B1(_076_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__o21ai_0 _139_ (
    .A1(counter2[0]),
    .A2(_029_),
    .B1(_030_),
    .Y(_004_[0])
  );
  sky130_fd_sc_hd__nand2_1 _140_ (
    .A(tx_valid),
    .B(_069_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__xor2_1 _141_ (
    .A(counter2[1]),
    .B(counter2[0]),
    .X(_032_)
  );
  sky130_fd_sc_hd__a21oi_1 _142_ (
    .A1(counter2[1]),
    .A2(_031_),
    .B1(_076_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__o21ai_0 _143_ (
    .A1(_031_),
    .A2(_032_),
    .B1(_033_),
    .Y(_004_[1])
  );
  sky130_fd_sc_hd__or4_1 _144_ (
    .A(counter2[2]),
    .B(counter2[1]),
    .C(counter2[0]),
    .D(_031_),
    .X(_034_)
  );
  sky130_fd_sc_hd__o31ai_1 _145_ (
    .A1(counter2[1]),
    .A2(counter2[0]),
    .A3(_031_),
    .B1(counter2[2]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand3_1 _146_ (
    .A(_077_),
    .B(_034_),
    .C(_035_),
    .Y(_004_[2])
  );
  sky130_fd_sc_hd__a21oi_1 _147_ (
    .A1(_069_),
    .A2(_074_),
    .B1(_070_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__a21o_1 _148_ (
    .A1(_069_),
    .A2(_074_),
    .B1(_070_),
    .X(_037_)
  );
  sky130_fd_sc_hd__a21oi_1 _149_ (
    .A1(counter1[0]),
    .A2(_036_),
    .B1(_076_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__o21ai_0 _150_ (
    .A1(counter1[0]),
    .A2(_071_),
    .B1(_038_),
    .Y(_003_[0])
  );
  sky130_fd_sc_hd__a32oi_1 _151_ (
    .A1(_008_),
    .A2(_015_),
    .A3(_037_),
    .B1(_071_),
    .B2(counter1[1]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor2_1 _152_ (
    .A(_076_),
    .B(_039_),
    .Y(_003_[1])
  );
  sky130_fd_sc_hd__a22oi_1 _153_ (
    .A1(counter1[2]),
    .A2(_071_),
    .B1(_010_),
    .B2(_037_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nor2_1 _154_ (
    .A(_076_),
    .B(_040_),
    .Y(_003_[2])
  );
  sky130_fd_sc_hd__o211ai_1 _155_ (
    .A1(_064_),
    .A2(_072_),
    .B1(_077_),
    .C1(_028_),
    .Y(_003_[3])
  );
  sky130_fd_sc_hd__nand4_1 _156_ (
    .A(counter2[2]),
    .B(counter2[1]),
    .C(counter2[0]),
    .D(_069_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand2_1 _157_ (
    .A(cs[0]),
    .B(_070_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a21oi_1 _158_ (
    .A1(ADD_DATA_checker),
    .A2(_074_),
    .B1(_042_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__a21oi_1 _159_ (
    .A1(_061_),
    .A2(_041_),
    .B1(_043_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__mux2_1 _160_ (
    .A0(rx_data[0]),
    .A1(bus[0]),
    .S(_075_),
    .X(_006_[0])
  );
  sky130_fd_sc_hd__mux2_1 _161_ (
    .A0(rx_data[1]),
    .A1(bus[1]),
    .S(_075_),
    .X(_006_[1])
  );
  sky130_fd_sc_hd__mux2_1 _162_ (
    .A0(rx_data[2]),
    .A1(bus[2]),
    .S(_075_),
    .X(_006_[2])
  );
  sky130_fd_sc_hd__mux2_1 _163_ (
    .A0(rx_data[3]),
    .A1(bus[3]),
    .S(_075_),
    .X(_006_[3])
  );
  sky130_fd_sc_hd__mux2_1 _164_ (
    .A0(rx_data[4]),
    .A1(bus[4]),
    .S(_075_),
    .X(_006_[4])
  );
  sky130_fd_sc_hd__mux2_1 _165_ (
    .A0(rx_data[5]),
    .A1(bus[5]),
    .S(_075_),
    .X(_006_[5])
  );
  sky130_fd_sc_hd__mux2_1 _166_ (
    .A0(rx_data[6]),
    .A1(bus[6]),
    .S(_075_),
    .X(_006_[6])
  );
  sky130_fd_sc_hd__mux2_1 _167_ (
    .A0(rx_data[7]),
    .A1(bus[7]),
    .S(_075_),
    .X(_006_[7])
  );
  sky130_fd_sc_hd__mux2_1 _168_ (
    .A0(rx_data[8]),
    .A1(bus[8]),
    .S(_075_),
    .X(_006_[8])
  );
  sky130_fd_sc_hd__mux2_1 _169_ (
    .A0(rx_data[9]),
    .A1(bus[9]),
    .S(_075_),
    .X(_006_[9])
  );
  sky130_fd_sc_hd__nand2_1 _170_ (
    .A(MISO),
    .B(_031_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__mux2i_1 _171_ (
    .A0(tx_data[0]),
    .A1(tx_data[4]),
    .S(counter2[2]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nor3_1 _172_ (
    .A(counter2[1]),
    .B(counter2[0]),
    .C(_045_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__mux4_2 _173_ (
    .A0(tx_data[2]),
    .A1(tx_data[3]),
    .A2(tx_data[6]),
    .A3(tx_data[7]),
    .S0(counter2[0]),
    .S1(counter2[2]),
    .X(_047_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _174_ (
    .A(counter2[2]),
    .SLEEP(tx_data[5]),
    .X(_048_)
  );
  sky130_fd_sc_hd__o21ai_0 _175_ (
    .A1(counter2[2]),
    .A2(tx_data[1]),
    .B1(counter2[0]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor3_1 _176_ (
    .A(counter2[1]),
    .B(_048_),
    .C(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a211oi_1 _177_ (
    .A1(counter2[1]),
    .A2(_047_),
    .B1(_050_),
    .C1(_046_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__o21ai_0 _178_ (
    .A1(_031_),
    .A2(_051_),
    .B1(_044_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor2_1 _179_ (
    .A(ss_n),
    .B(_073_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nor3_1 _180_ (
    .A(ss_n),
    .B(_073_),
    .C(_042_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor4b_1 _181_ (
    .A(cs[2]),
    .B(cs[1]),
    .C(ss_n),
    .D_N(cs[0]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _182_ (
    .A(ss_n),
    .B(_077_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__a32o_1 _183_ (
    .A1(ADD_DATA_checker),
    .A2(MOSI),
    .A3(_054_),
    .B1(cs[0]),
    .B2(cs[2]),
    .X(_056_)
  );
  sky130_fd_sc_hd__o31a_1 _184_ (
    .A1(_053_),
    .A2(_055_),
    .A3(_056_),
    .B1(rst_n),
    .X(_005_[0])
  );
  sky130_fd_sc_hd__o21ai_0 _185_ (
    .A1(cs[2]),
    .A2(_052_),
    .B1(cs[1]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__o21ai_0 _186_ (
    .A1(ADD_DATA_checker),
    .A2(_062_),
    .B1(_054_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a21boi_0 _187_ (
    .A1(_057_),
    .A2(_058_),
    .B1_N(rst_n),
    .Y(_005_[1])
  );
  sky130_fd_sc_hd__nand2_1 _188_ (
    .A(ss_n),
    .B(_065_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__a32oi_1 _189_ (
    .A1(_061_),
    .A2(MOSI),
    .A3(_054_),
    .B1(_059_),
    .B2(cs[2]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _190_ (
    .A(rst_n),
    .SLEEP(_060_),
    .X(_005_[2])
  );
  sky130_fd_sc_hd__dfrtp_1 _191_ (
    .CLK(clk),
    .D(_002_),
    .Q(MISO),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _192_ (
    .CLK(clk),
    .D(_006_[0]),
    .Q(rx_data[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _193_ (
    .CLK(clk),
    .D(_006_[1]),
    .Q(rx_data[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _194_ (
    .CLK(clk),
    .D(_006_[2]),
    .Q(rx_data[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _195_ (
    .CLK(clk),
    .D(_006_[3]),
    .Q(rx_data[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _196_ (
    .CLK(clk),
    .D(_006_[4]),
    .Q(rx_data[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _197_ (
    .CLK(clk),
    .D(_006_[5]),
    .Q(rx_data[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _198_ (
    .CLK(clk),
    .D(_006_[6]),
    .Q(rx_data[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _199_ (
    .CLK(clk),
    .D(_006_[7]),
    .Q(rx_data[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _200_ (
    .CLK(clk),
    .D(_006_[8]),
    .Q(rx_data[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _201_ (
    .CLK(clk),
    .D(_006_[9]),
    .Q(rx_data[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _202_ (
    .CLK(clk),
    .D(_007_),
    .Q(rx_valid),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _203_ (
    .CLK(clk),
    .D(_001_),
    .Q(ADD_DATA_checker),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _204_ (
    .CLK(clk),
    .D(_003_[0]),
    .Q(counter1[0]),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _205_ (
    .CLK(clk),
    .D(_003_[1]),
    .Q(counter1[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _206_ (
    .CLK(clk),
    .D(_003_[2]),
    .Q(counter1[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _207_ (
    .CLK(clk),
    .D(_003_[3]),
    .Q(counter1[3]),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _208_ (
    .CLK(clk),
    .D(_004_[0]),
    .Q(counter2[0]),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _209_ (
    .CLK(clk),
    .D(_004_[1]),
    .Q(counter2[1]),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _210_ (
    .CLK(clk),
    .D(_004_[2]),
    .Q(counter2[2]),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _211_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(bus[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _212_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(bus[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _213_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(bus[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _214_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(bus[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _215_ (
    .CLK(clk),
    .D(_000_[4]),
    .Q(bus[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _216_ (
    .CLK(clk),
    .D(_000_[5]),
    .Q(bus[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _217_ (
    .CLK(clk),
    .D(_000_[6]),
    .Q(bus[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _218_ (
    .CLK(clk),
    .D(_000_[7]),
    .Q(bus[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _219_ (
    .CLK(clk),
    .D(_000_[8]),
    .Q(bus[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _220_ (
    .CLK(clk),
    .D(_000_[9]),
    .Q(bus[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _221_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_083_[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _222_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_083_[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _223_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_083_[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _224_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_083_[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _225_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_081_[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _226_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_081_[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _227_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_081_[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _228_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_081_[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _229_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_082_[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _230_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_082_[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _231_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_082_[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _232_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_082_[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _233_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_084_[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _234_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_084_[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _235_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_084_[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _236_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_084_[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _237_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_084_[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _238_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_084_[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _239_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_084_[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _240_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_084_[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _241_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_084_[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _242_ (
    .CLK(clk),
    .D(1'hx),
    .Q(_084_[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfxtp_1 _243_ (
    .CLK(clk),
    .D(_005_[0]),
    .Q(cs[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _244_ (
    .CLK(clk),
    .D(_005_[1]),
    .Q(cs[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _245_ (
    .CLK(clk),
    .D(_005_[2]),
    .Q(cs[2])
  );
endmodule

module spi_to_sram_wrapper(clk, rst_n, ss_n, MOSI, MISO, debug_addr, debug_din, debug_dout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  output MISO;
  wire MISO;
  input MOSI;
  wire MOSI;
  input clk;
  wire clk;
  wire csb0;
  output [7:0] debug_addr;
  wire [7:0] debug_addr;
  output [7:0] debug_din;
  wire [7:0] debug_din;
  output [7:0] debug_dout;
  wire [7:0] debug_dout;
  wire [7:0] dout0;
  input rst_n;
  wire rst_n;
  wire [9:0] rx_data;
  wire rx_valid;
  wire [7:0] sram_addr;
  wire [7:0] sram_din;
  input ss_n;
  wire ss_n;
  wire [7:0] tx_data;
  wire tx_valid;
  wire web0;
  sky130_fd_sc_hd__nand2b_1 _21_ (
    .A_N(rx_data[9]),
    .B(rx_valid),
    .Y(_18_)
  );
  sky130_fd_sc_hd__o22a_1 _22_ (
    .A1(web0),
    .A2(rx_valid),
    .B1(_18_),
    .B2(rx_data[8]),
    .X(_01_)
  );
  sky130_fd_sc_hd__o21a_1 _23_ (
    .A1(rx_valid),
    .A2(csb0),
    .B1(_18_),
    .X(_00_)
  );
  sky130_fd_sc_hd__nand3b_1 _24_ (
    .A_N(rx_data[9]),
    .B(rx_valid),
    .C(rst_n),
    .Y(_19_)
  );
  sky130_fd_sc_hd__nor4bb_1 _25_ (
    .A(rx_data[8]),
    .B(rx_data[9]),
    .C_N(rx_valid),
    .D_N(rst_n),
    .Y(_20_)
  );
  sky130_fd_sc_hd__mux2_1 _26_ (
    .A0(sram_din[0]),
    .A1(rx_data[0]),
    .S(_20_),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_1 _27_ (
    .A0(sram_din[1]),
    .A1(rx_data[1]),
    .S(_20_),
    .X(_03_)
  );
  sky130_fd_sc_hd__mux2_1 _28_ (
    .A0(sram_din[2]),
    .A1(rx_data[2]),
    .S(_20_),
    .X(_04_)
  );
  sky130_fd_sc_hd__mux2_1 _29_ (
    .A0(sram_din[3]),
    .A1(rx_data[3]),
    .S(_20_),
    .X(_05_)
  );
  sky130_fd_sc_hd__mux2_1 _30_ (
    .A0(sram_din[4]),
    .A1(rx_data[4]),
    .S(_20_),
    .X(_06_)
  );
  sky130_fd_sc_hd__mux2_1 _31_ (
    .A0(sram_din[5]),
    .A1(rx_data[5]),
    .S(_20_),
    .X(_07_)
  );
  sky130_fd_sc_hd__mux2_1 _32_ (
    .A0(sram_din[6]),
    .A1(rx_data[6]),
    .S(_20_),
    .X(_08_)
  );
  sky130_fd_sc_hd__mux2_1 _33_ (
    .A0(sram_din[7]),
    .A1(rx_data[7]),
    .S(_20_),
    .X(_09_)
  );
  sky130_fd_sc_hd__mux2_1 _34_ (
    .A0(rx_data[0]),
    .A1(sram_addr[0]),
    .S(_19_),
    .X(_10_)
  );
  sky130_fd_sc_hd__mux2_1 _35_ (
    .A0(rx_data[1]),
    .A1(sram_addr[1]),
    .S(_19_),
    .X(_11_)
  );
  sky130_fd_sc_hd__mux2_1 _36_ (
    .A0(rx_data[2]),
    .A1(sram_addr[2]),
    .S(_19_),
    .X(_12_)
  );
  sky130_fd_sc_hd__mux2_1 _37_ (
    .A0(rx_data[3]),
    .A1(sram_addr[3]),
    .S(_19_),
    .X(_13_)
  );
  sky130_fd_sc_hd__mux2_1 _38_ (
    .A0(rx_data[4]),
    .A1(sram_addr[4]),
    .S(_19_),
    .X(_14_)
  );
  sky130_fd_sc_hd__mux2_1 _39_ (
    .A0(rx_data[5]),
    .A1(sram_addr[5]),
    .S(_19_),
    .X(_15_)
  );
  sky130_fd_sc_hd__mux2_1 _40_ (
    .A0(rx_data[6]),
    .A1(sram_addr[6]),
    .S(_19_),
    .X(_16_)
  );
  sky130_fd_sc_hd__mux2_1 _41_ (
    .A0(rx_data[7]),
    .A1(sram_addr[7]),
    .S(_19_),
    .X(_17_)
  );
  sky130_fd_sc_hd__dfxtp_1 _42_ (
    .CLK(clk),
    .D(_02_),
    .Q(sram_din[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _43_ (
    .CLK(clk),
    .D(_03_),
    .Q(sram_din[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _44_ (
    .CLK(clk),
    .D(_04_),
    .Q(sram_din[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _45_ (
    .CLK(clk),
    .D(_05_),
    .Q(sram_din[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _46_ (
    .CLK(clk),
    .D(_06_),
    .Q(sram_din[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _47_ (
    .CLK(clk),
    .D(_07_),
    .Q(sram_din[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _48_ (
    .CLK(clk),
    .D(_08_),
    .Q(sram_din[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _49_ (
    .CLK(clk),
    .D(_09_),
    .Q(sram_din[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _50_ (
    .CLK(clk),
    .D(_10_),
    .Q(sram_addr[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _51_ (
    .CLK(clk),
    .D(_11_),
    .Q(sram_addr[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _52_ (
    .CLK(clk),
    .D(_12_),
    .Q(sram_addr[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _53_ (
    .CLK(clk),
    .D(_13_),
    .Q(sram_addr[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _54_ (
    .CLK(clk),
    .D(_14_),
    .Q(sram_addr[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _55_ (
    .CLK(clk),
    .D(_15_),
    .Q(sram_addr[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _56_ (
    .CLK(clk),
    .D(_16_),
    .Q(sram_addr[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _57_ (
    .CLK(clk),
    .D(_17_),
    .Q(sram_addr[7])
  );
  sky130_fd_sc_hd__dfstp_2 _58_ (
    .CLK(clk),
    .D(_00_),
    .Q(csb0),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _59_ (
    .CLK(clk),
    .D(_01_),
    .Q(web0),
    .SET_B(rst_n)
  );
  SPI_SLAVE spi (
    .MISO(MISO),
    .MOSI(MOSI),
    .clk(clk),
    .rst_n(rst_n),
    .rx_data(rx_data),
    .rx_valid(rx_valid),
    .ss_n(ss_n),
    .tx_data(dout0),
    .tx_valid(tx_valid)
  );
  sram_8_256_sky130A sram (
    .addr0(sram_addr),
    .clk0(clk),
    .csb0(csb0),
    .din0(sram_din),
    .dout0(dout0),
    .web0(web0)
  );
  assign debug_addr = sram_addr;
  assign debug_din = sram_din;
  assign debug_dout = dout0;
  assign tx_data = dout0;
endmodule
